# Generated by Django 5.0.7 on 2024-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='City',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Pincode',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='State',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='City',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Pincode',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='State',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
