# Generated by Django 5.0.7 on 2024-07-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_address_doctor_city_doctor_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='ProfilePiture',
            new_name='ProfilePicture',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='ProfilePiture',
            new_name='ProfilePicture',
        ),
    ]
