# Generated by Django 5.0.7 on 2024-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profilepiture_doctor_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ProfilePicture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ProfilePicture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
