# Generated by Django 5.0.7 on 2024-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(default='00.00'),
        ),
    ]
