# Generated by Django 5.0.7 on 2024-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(),
        ),
    ]
