# Generated by Django 5.0.7 on 2024-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Speciality',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
