# Generated by Django 5.0.7 on 2024-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Did',
            field=models.IntegerField(default=None),
        ),
    ]
