# Generated by Django 5.0.7 on 2024-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_doctor_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Did',
            field=models.IntegerField(unique=True),
        ),
    ]
